function createNewRaceWeek() {
    // This function now acts as a UI renderer for the race week data
    // generated by the ProgressionManager.

    // Check if wordlists are loaded, if not wait for them
    if (!window.racerNamePrefixes || !window.racerNameSuffixes) {
        console.log('Waiting for wordlists to load...');
        setTimeout(() => createNewRaceWeek(), 100);
        return;
    }

    const raceWeekInfoSection1 = document.getElementById("raceWeekInfoSection1"); 
    const raceWeekInfoSection2 = document.getElementById("raceWeekInfoSection2");
    const raceWeekInfoSection3 = document.getElementById("raceWeekInfoSection3");
    raceWeekInfoSection1.innerHTML = "";
    raceWeekInfoSection2.innerHTML = "";
    raceWeekInfoSection3.innerHTML = "";

    const raceWeek = gameState.raceWeek;

    if (!raceWeek || !raceWeek.races || raceWeek.races.length === 0) {
        console.error("UI Update: No race week data found in gameState to display.");
        raceWeekInfoSection2.innerHTML = "Error: Race Week data could not be generated.";
        return;
    }

    // Update UI from gameState
    document.getElementById("raceWeekNumber").innerHTML = raceWeek.id;
    
    // Create UI for each race in the week
    raceWeek.races.forEach((race, raceIndex) => {
        const track = race.track;
        const weather = race.weather;
        const icon = ({sunny:'☀️',rainy:'🌧️',windy:'💨',cloudy:'☁️',dusty:'🌫️',stormy:'⛈️',snowy:'❄️',foggy:'🌁'})[weather] || '⛅';

        const weekContainer = document.createElement('div');
        weekContainer.className = 'race-week-container';

        // Highlight first race as the current one
        if (raceIndex === 0) {
            weekContainer.classList.add('current-week');
        } else {
            weekContainer.classList.add('past-week');
        }

        const weekHeader = document.createElement('div');
        weekHeader.className = 'race-week-header';
        weekHeader.innerHTML = `
            <h4>Race ${raceIndex + 1}: ${track.name}</h4>
            <div class="track-info">
                <span class="track-length">${track.sections.length * gameState.settings.trackProperties.segmentsPerSection} segments</span>
                <span class="ground-types">${getUniqueGroundTypes(track.sections).join(', ')}</span>
                <span class="weather-badge">${icon} ${weather}</span>
            </div>
        `;

        const racersList = document.createElement('ul');
        racersList.className = 'racers-list';

        race.racers.forEach(racer => {
            const racerListItem = document.createElement('li');
            racerListItem.append(DOMUtils.createRacerGuiElement(racer.id));
            racersList.appendChild(racerListItem);
        });

        weekContainer.appendChild(weekHeader);
        weekContainer.appendChild(racersList);
        raceWeekInfoSection1.appendChild(weekContainer);
    });
}

// Helper function to get unique ground types from track sections
function getUniqueGroundTypes(sections) {
    const groundTypes = {};
    sections.forEach(section => {
        groundTypes[section] = true;
    });
    return Object.keys(groundTypes);
}